sudo: false
language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - cmake

before_install:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_INSTALL_PREFIX=/home/travis/build/incomingstick/local/bin ..
  - make check
  - make install