sudo: false
language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false

before_install:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_INSTALL_PREFIX=/home/travis/build/incomingstick/local/bin ..
  - make check
  - make install